
/**************************************************************
 *	
 *	game_loop, 8 bit, 8000Hz,
 *	1 channel, 46666 bytes/channel
 *	Total Size: 1 * 46666 + 4 (header) = 46710 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Garrett\Documents\2261\final project\GarrettStache_FinalProject\game_loop.wav
 *	Time-stamp: Sat Nov 08 11:10:04 2014
 *	
 **************************************************************/

#ifndef __GAME_LOOPH__
#define __GAME_LOOPH__

#define GAME_LOOPFREQ 8000
#define GAME_LOOPLEN 46666

extern const unsigned char game_loop[46666];

#endif /* __GAME_LOOPH__ */
