
/**************************************************************
 *	
 *	Kung_Fu, 8 bit, 8000Hz,
 *	1 channel, 102431 bytes/channel
 *	Total Size: 1 * 102431 + 4 (header) = 102475 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Garrett\Documents\2261\final project\GarrettStache_FinalProject\Kung Fu.wav
 *	Time-stamp: Sat Nov 08 11:09:58 2014
 *	
 **************************************************************/

#ifndef __KUNG_FUH__
#define __KUNG_FUH__

#define KUNG_FUFREQ 8000
#define KUNG_FULEN 102431

extern const unsigned char Kung_Fu[102431];

#endif /* __KUNG_FUH__ */
