
/**************************************************************
 *	
 *	power_up, 8 bit, 8000Hz,
 *	1 channel, 29376 bytes/channel
 *	Total Size: 1 * 29376 + 4 (header) = 29472 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Garrett\Documents\2261\final project\GarrettStache_FinalProject\power_up.wav
 *	Time-stamp: Sat Nov 08 11:09:51 2014
 *	
 **************************************************************/

#ifndef __POWER_UPH__
#define __POWER_UPH__

#define POWER_UPFREQ 8000
#define POWER_UPLEN 29376

extern const unsigned char power_up[29376];

#endif /* __POWER_UPH__ */
