
/**************************************************************
 *	
 *	super_slice, 8 bit, 8000Hz,
 *	1 channel, 7768 bytes/channel
 *	Total Size: 1 * 7768 + 4 (header) = 7864 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Garrett\Documents\2261\final project\GarrettStache_FinalProject\super_slice.wav
 *	Time-stamp: Thu Nov 13 11:44:01 2014
 *	
 **************************************************************/

#ifndef __SUPER_SLICEH__
#define __SUPER_SLICEH__

#define SUPER_SLICEFREQ 8000
#define SUPER_SLICELEN 7768

extern const unsigned char super_slice[7768];

#endif /* __SUPER_SLICEH__ */
