
/**************************************************************
 *	
 *	Sword_Swing, 8 bit, 8000Hz,
 *	1 channel, 1960 bytes/channel
 *	Total Size: 1 * 1960 + 4 (header) = 2004 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Garrett\Documents\2261\final project\GarrettStache_FinalProject\Sword_Swing.wav
 *	Time-stamp: Sat Nov 08 11:09:18 2014
 *	
 **************************************************************/

#ifndef __SWORD_SWINGH__
#define __SWORD_SWINGH__

#define SWORD_SWINGFREQ 8000
#define SWORD_SWINGLEN 1960

extern const unsigned char Sword_Swing[1960];

#endif /* __SWORD_SWINGH__ */
