
/**************************************************************
 *	
 *	Swords_Clashing, 8 bit, 8000Hz,
 *	1 channel, 6814 bytes/channel
 *	Total Size: 1 * 6814 + 4 (header) = 6858 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Garrett\Documents\2261\final project\GarrettStache_FinalProject\Swords_Clashing.wav
 *	Time-stamp: Sat Nov 08 11:09:11 2014
 *	
 **************************************************************/

#ifndef __SWORDS_CLASHINGH__
#define __SWORDS_CLASHINGH__

#define SWORDS_CLASHINGFREQ 8000
#define SWORDS_CLASHINGLEN 6814

extern const unsigned char Swords_Clashing[6814];

#endif /* __SWORDS_CLASHINGH__ */
