
/**************************************************************
 *	
 *	victory_song, 8 bit, 8000Hz,
 *	1 channel, 39212 bytes/channel
 *	Total Size: 1 * 39212 + 4 (header) = 39256 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Garrett\Documents\2261\final project\GarrettStache_FinalProject\victory_song.wav
 *	Time-stamp: Sat Nov 08 11:08:31 2014
 *	
 **************************************************************/

#ifndef __VICTORY_SONGH__
#define __VICTORY_SONGH__

#define VICTORY_SONGFREQ 8000
#define VICTORY_SONGLEN 39212

extern const unsigned char victory_song[39212];

#endif /* __VICTORY_SONGH__ */
